input:
  folder: data\raw\expt_TMPTMApPDMSEEC_HighRes
  indices: [1]
  rename: ['1TMPTMA-2pPDMSEEC Exit']
  
analysistype: 'positional' # 'positional' or 'non-positional'
positionalOutput: 'map' # if positional: 'map' or '3D height map'
nonpositional_indices: [0, 20, 40]  # Indices to treat as non-positional if a positional dataset
nonpositional_rename: ['Pos 1', 'Pos 2', 'Pos 3']  # Rename selection for non-positional data
positional2D: false #if positional data should be treated as 2D (i.e. a line scan)

plotting:
  focus_range: [634, 1760]
  offset:
      enabled: false
      step: 0.0012  # vertical offset between spectra
  mappingmode: "pixel" # "pixel", "scatter", "interp" or "3d" or "slice" or "depth"
  fixedpeakratio: [0,10]
  fixed_colorbar: false  # Fix color bar min/max across all samples
  map_limits:
    enabled: false # set true to enforce manual limits below
    intensity: [5e7, 2e8]  # manual y-limit for integrated intensity maps
    ratio: [0.5, 0.75]  # manual y-limit for peak ratio maps
  map_subset:
    enabled: false  # set true to plot only the first part of the map
    first_n_points: null  # if null, uses the first half of the map; set an integer to use the first N points

processing:
  baseline: true
  normalize: true
  smoothing: false
  show_baseline: true

peaks:
  tolerance: 2
  intensity_threshold: 1000000
  ranges:
    range1:
      bounds: [630, 720]
      peaks: [650, 669, 681, 705]
    range2:
      bounds: [1680, 1770]
      peaks: [1720,1744]

ratios:
  - [1720, 681]