
peaks:
  peak1: [1700, 1740]
  peak2: [670, 695]

processing:
  baseline: true
  normalize: true
  smoothing: false

input:
  folder: data/raw
  indices: [0,1,2,3,4,5]
  rename: ["mat 1", "mat 2", "mat 3", "wg 1", "wg 2", "wg 3"]
