input:
  folder: data/raw/expt_AFMIRblend
  indices: [0]
  rename: ['WEL']

plotting:
  focus_range: [300, 3000]
  offset:
      enabled: true
      step: 0.0012  # vertical offset between spectra

processing:
  baseline: true
  normalize: true
  smoothing: false
  show_baseline: true

peaks:
  tolerance: 2

  ranges:
    range1:
      bounds: [630, 720]
      peaks: [650, 669, 681, 705]

    range2:
      bounds: [1680, 1770]
      peaks: [1720]

ratios:
  - [1720, 681]

